### ISSUE TITLE
It should definitely ask for a password if failed to obtain key from TPM

### ISSUE THREAD

**Issue by alttch** [fox-it/linux-luks-tpm-boot#15]
the simply way: just add in getsecret.sh
--
if [ "x$PIPESTATUS" == "x255" ]; then
  (>&2 echo -n "Can't obtain TPM key. Enter password: ")
 read -s PW
 echo -n ${PW}
 exit
fi
--
after tpm_nvread. PIPESTATUS & read require bash so change header to #!/bin/bash and add it to tpm-hook as well. plus add /usr/bin/head, it isn't included in initramfs in Ubuntu by default.

it should check for the exactly 255 exit code, to avoid asking for a password if tcsd crashed instead of just restarting the script.

**Comment by morbitzer** [comment]
That seems to be a nice solution. Could you create a pull request for that? 
No need to include the /usr/bin/head/, we can replace head with dd as suggested in issue #16

**Comment by dirkjanm** [comment]
This was added in 4095408
