### ISSUE TITLE
line 9: head: command not found

### ISSUE THREAD

**Issue by joe-bowman** [fox-it/linux-luks-tpm-boot#16]
OS: Ubuntu 18.04 (bionic beaver)

When ./getsecret.sh is run during the boot process, `head` is not available so the script fails to pull the secret from the TPM.

However, dd _does_ appear to be available, so replacing `head -C $SIZE` with `dd if=/dev/stdin of=/dev/stdout bs=1 count=$SIZE 2>/dev/null` appears to do the trick.

Any reason we shouldn't use `dd` in preference to `head`?

**Comment by morbitzer** [comment]
Seems like a good fix. Head is included in the initramfs by default in Debian, that's why I used that. But as this does not seem to be the case with all distros, this is a good solution. 
@dirkjanm, please accept the pull request.
