### ISSUE TITLE
Error when using password containing backslash \

### ISSUE THREAD

**Issue by Lordcorvin1** [fox-it/linux-luks-tpm-boot#18]
In seal-nvram.sh I was getting Tspi_NV_DefineSpace failed: 0x00000001 - layer=tpm, code=0001 (1), Authentication failed whenever entering a password.
Realized it's due to backslash in my password.
Shouldn't -r be added to read command to negate this? I tested it on my machine and was able to use the script. Will it have consequences?

**Comment by morbitzer** [comment]
Yes, I guess that makes sense. Could you create a pull request that includes the -r switch for the read command?

**Comment by Lordcorvin1** [comment]
Created pull request. Topic can be closed after the merge

**Comment by dirkjanm** [comment]
Added in #21
