### ISSUE TITLE
grub_TPM_measure_string

### ISSUE THREAD

**Issue by apathub** [fox-it/linux-luks-tpm-boot#25]
I followed the readme, and I have an issue right after the TrustedGRUB2 installation.
I rebooted the system, and the grub doesn't load at all.
Here is what I get
 ```
error: symbol 'grub_TPM_measure_string' not found.
Entering rescue mode...
grub rescue>
```
Do you have any ideas how I can recover my system?

**Comment by morbitzer** [comment]
Seems like something went wrong during the TrustedGRUB2 installation - but it's hard to say what exactly without any error messages. 
To recover from such faults, I use the installation media from my distro. They usually have a repair mode, which allows to reinstall the bootloader. 

Good luck!

**Comment by apathub** [comment]
yeah, I used the installation media, and I repaired the boot loader! 
Thanks!
