### ISSUE TITLE
User "tss" not found, please add this user manually.

### ISSUE THREAD

**Issue by UltraCodeX** [fox-it/linux-luks-tpm-boot#3]
Hello, 
It appears that on boot, the tpm_nvread command fails with a communication error.

When I ran tcsd -f, it is telling me that the user "tss" doesn't exist but I know for a fact it does. I tried deleting the user and group tss and readding as a normal user and system user but no difference. Just to test, I deleted the group tss and then in initramfs, tcsd picked up that the group was not there and gave the same error except it stated the group didn't exist. When I logged into my system and readded group tss and user tss and reboot, it is telling me the user doesnt exist. I can systemctl start trousers when logged into the system and tcsd -f runs just fine and I can read the PCR wirh the tmp_nvread command. I followed thw tutorial exactly and didn't do anything special. Any assistance is appreciated, thanks!

P.S When the trousers service is stopped when I'm logged into the system, tpm_nvread gives a communication error. As soon as I start the trousers service, the command works. So clearly same error in the initramfs because tcsd isn't starting.

**Comment by UltraCodeX** [comment]
I finally had the time to test this out again, and now... it finally works! 
After CelmPi's merge, I was able to follow the instructions posted by Fox-IT exactly and it worked like a charm, no more "tss user not found" issue. Can't thank you guys enough, don't know where I would have started without this tutorial. Issue is resolved, cheers!

**Comment by morbitzer** [comment]
Great to hear. Thanks to CelmPi!
