### ISSUE TITLE
Bad memory index

### ISSUE THREAD

**Issue by Andy944** [fox-it/linux-luks-tpm-boot#8]
Hey guys, I have an issue during command
sudo /sbin/seal-nvram.sh -z
It gives me an error
Owner password: Tspi_NV_DefineSpace failed: 0x00000002 - layer=tpm, code=0002 (2), Bad memory index

I have Ubuntu 16.04, TPM 1.2

Any ideas what is wrong?

Thanks!

**Comment by morbitzer** [comment]
Hi Andy, 
could you try manually executing the commands in `seal-nvram.sh` to see which one is causing the problem?

I'm assuming it's the `tpm_nvdefine` command. So could you try to manually execute 
`tpm_nvdefine -i 1 -s 256 -p "OWNERWRITE|READ_STCLEAR" -z` ? 

It might also be worth trying different index/size/permission!

**Comment by Andy944** [comment]
Yes, set manually different index solved the issue, thanks!
